let reportData=null;
function showTab(id){document.querySelectorAll('.panel').forEach(p=>p.classList.add('hidden'));document.getElementById(id).classList.remove('hidden'); if(id==='saved') loadSaved();}
function addViolation(desc='', note=''){const wrap=document.getElementById('violations');const i=wrap.children.length+1;const div=document.createElement('div');div.className='violation-card';div.innerHTML=`<b>مخالفة ${i}</b><label>وصف المخالفة<input class="vdesc" value="${desc}" placeholder="مثال: عدم ارتداء معدات الوقاية الشخصية"></label><label>صورة المخالفة<input class="vimg" type="file" accept="image/*"></label><label>ملاحظات<textarea class="vnote" placeholder="ملاحظات إضافية">${note}</textarea></label>`;wrap.appendChild(div)}
addViolation('عدم ارتداء معدات الوقاية الشخصية','');addViolation('تمديدات كهربائية مكشوفة','');addViolation('عدم توفر طفاية حريق صالحة','');
function fileToDataURL(file){return new Promise(res=>{if(!file)return res('');const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(file)})}
async function collect(){const cards=[...document.querySelectorAll('.violation-card')];const violations=[];for(const c of cards){violations.push({desc:c.querySelector('.vdesc').value,note:c.querySelector('.vnote').value,img:await fileToDataURL(c.querySelector('.vimg').files[0])})}return{projectName:projectName.value,safetyOfficer:safetyOfficer.value,projectManager:projectManager.value,notes:notes.value,violations}}
async function generateReport(){const raw=await collect();const res=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(raw)});const data=await res.json();data.violations=data.violations.map((v,i)=>({...v,img:raw.violations[i]?.img||''}));reportData=data;renderReport(data)}
function renderReport(d){document.getElementById('report').innerHTML=`<div class="hse-report"><div class="report-title"><div><h2>تقرير صحة وسلامة مهنية</h2><p>منشئ موقع الذكاء الاصطناعي: سامي الاسمري</p></div><div class="badge">HSE REPORT</div></div><div class="section-head"><span class="num">1</span> اسم المشروع <b>${d.projectName||''}</b></div><div class="section-head"><span class="num">2</span> المخالفات المرصودة</div><table class="viol-table"><thead><tr><th style="width:8%">م</th><th>وصف المخالفة</th><th>صورة المخالفة</th><th>الملاحظات</th></tr></thead><tbody>${(d.violations||[]).map((v,i)=>`<tr><td>${i+1}</td><td>${v.desc||''}</td><td>${v.img?`<img src="${v.img}">`:'-'}</td><td>${v.note||'<div class="lines"></div>'}</td></tr>`).join('')}</tbody></table><div class="bottom-grid"><div class="box"><h3>3. ملاحظات عامة</h3><div class="box-content">${d.generalNotes||''}</div></div><div class="box"><h3>4. التوصيات العامة</h3><div class="box-content"><ul>${(d.recommendations||[]).map(x=>`<li>${x}</li>`).join('')}</ul></div></div></div><div class="signs"><div class="sign"><h3>مدير المشروع</h3><p>الاسم: ${d.projectManager||''}</p><p>التوقيع:</p><div class="sign-line"></div></div><div class="sign"><h3>مسؤول السلامة</h3><p>الاسم: ${d.safetyOfficer||''}</p><p>التوقيع:</p><div class="sign-line"></div></div></div></div>`}
async function saveReport(){if(!reportData) await generateReport();await fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(reportData)});alert('تم حفظ التقرير بنجاح')}
async function loadSaved(){const res=await fetch('/api/reports');const rows=await res.json();savedList.innerHTML=rows.map(r=>`<div class="saved-item"><b>${r.projectName||'تقرير'}</b><p>${new Date(r.createdAt).toLocaleString('ar-SA')}</p></div>`).join('')||'لا توجد تقارير محفوظة بعد'}
